name: Build
description: Build the project

on:
  push:
  pull_request:
  workflow_run:
    workflows: ["Release"]
    types: [requested]
    branches:
      - 'main'

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Set up
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
  docs:
    name: Documentation
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Build documentation
      run: make doc
    - name: Upload documentation
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs/
  lint:
    name: Linting
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Run linter
      run: make lint
  type:
    name: Typing
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Run type checker
      run: make type
  test:
    name: Testing
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Run unit tests
      run: make test
  package:
    name: Package distribution
    needs: [lint, test, type]
    runs-on: ubuntu-latest
    steps:
    - name: Build package distribution
      run: make package
    - name: Upload package distribution
      uses: actions/upload-artifact@v3
      with:
        name: distribution
        path: dist/
