name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  pages:
    name: Documentation to GitHub Pages
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      id-token: write
      pages: write
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
  testpypi:
    name: Publish to TestPyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/${{ github.event.repository.name }}
    permissions:
      id-token: write
    steps:
    - name: Download distribution
      uses: actions/download-artifact@v4
      with:
        name: distribution
        path: dist/
    - name: Upload to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
